services:
  postgres-db:
    image: postgres:16.4-alpine3.20
    restart: always
    environment:
      POSTGRES_PASSWORD: app_citas
      POSTGRES_DB: app_citas
      POSTGRES_USER: app_citas
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"      